### ISSUE TITLE
How to calculate the accuracy of the fusion model?

### ISSUE THREAD

**Issue by izhangh** [alexander-rakhlin/ICIAR2018#10]
How to calculate the accuracy of the fusion model?
How to calculate the standard deviation?
I ran `train_lgbm.py` but could not reach the accuracy and std of the fusion model.
Thank you!

**Comment by izhangh** [comment]
How is the model fusion implemented? I did not find the corresponding code. Please help me, thank you

**Comment by alexander-rakhlin** [comment]
Both questions are covered in README:
> 4. To combine predictions across all models, seeds and augmentations, and crossvalidate across all folds run:
> 
> python crossvalidate_blending.py

**Comment by izhangh** [comment]
I was so careless, thank you very much



发自我的小米手机
在 Alexander Rakhlin <notifications@github.com>，2018年6月18日 下午3:58写道：

Both questions are covered in README:

  1.  To combine predictions across all models, seeds and augmentations, and crossvalidate across all folds run:

python crossvalidate_blending.py

**Comment by alexander-rakhlin** [comment]
No problem, thank you for your interest,
