### ISSUE TITLE
lightgbm.basic.LightGBMError: Tree model should contain num_cat field

### ISSUE THREAD

**Issue by greatpak** [alexander-rakhlin/ICIAR2018#12]
Hi,
I try lots of things but got the same error. PLease guide me.

Thank You

**Comment by alexander-rakhlin** [comment]
Hi,
This is a version compatibility issue. I am trying to figure out with LightGBM developers how to address it and come back if solution is found. Meanwhile you can try older versions of LightGBM ~2.0.1

**Comment by alexander-rakhlin** [comment]
Please re-download `download_models.py` and run it as instructed in README. This downloads LightGBM models updated to recent version, and everything should work

**Comment by toandang** [comment]
Hi Alexander,

I still got the same issue although I have download the latest model and install lightgbm version 2.1.2.
Python 3.6.3 (v3.6.3:2c5fed86e0, Oct  3 2017, 00:32:08) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import lightgbm
p>>> print(lightgbm.__version__)
2.1.2

Test:
ICIAR2018 git:(master) ✗ /Library/Frameworks/Python.framework/Versions/3.6/bin/python3 submission.py 
[LightGBM] [Fatal] Tree model should contain num_cat field
Traceback (most recent call last):
  File "submission.py", line 63, in <module>
    model = pickle.load(f)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/lightgbm/basic.py", line 1401, in __setstate__
    ctypes.byref(handle)))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/lightgbm/basic.py", line 49, in _safe_call
    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))
lightgbm.basic.LightGBMError: Tree model should contain num_cat field

Thanks.
