### ISSUE TITLE
Is there a bug in H&E augmentation?

### ISSUE THREAD

**Issue by hbk16** [alexander-rakhlin/ICIAR2018#14]
I've notice a possible bug in line 127 of feature_extractor.py.  `img_aug = np.dot(C, M) * r`
I guess it should be `img_aug = np.dot(C * r, M)`
where `C` is in the H&E color space and multiplication of HE channel should be applied on that.

**Comment by alexander-rakhlin** [comment]
Thank you, that makes sense. This part was converted from the Matlab code provided by the challenge organizers and authors of  ["Classification of breast cancer histology images using Convolutional Neural Networks"](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0177544) I can not find original Matlab code so it's difficult to tell whether it was original error(?) or introduced by ourselves. Thanks again.
