### ISSUE TITLE
 No such file or directory: 'data/folds-10.pkl'

### ISSUE THREAD

**Issue by sara-kassani** [alexander-rakhlin/ICIAR2018#7]
python crossvalidate_blending.py
Traceback (most recent call last):
  File "crossvalidate_blending.py", line 24, in <module>
    with open("data/folds-10.pkl", "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/folds-10.pkl'

**Comment by alexander-rakhlin** [comment]
You need to make sure your directory structure is in accordance with README and `data` folder contains `folds-10.pkl`
