### ISSUE TITLE
Input size of images

### ISSUE THREAD

**Issue by Suvi-dha** [alexander-rakhlin/ICIAR2018#8]
Hi, I want to transfer learn your trained models to another network, But from the paper I cannot grasp the size of  the input data you have used to train your networks.  If the data you used is of arbitrary size then what should be size of my dataset if I want to use your trained model weights? Or the weights cannot be used for transfer learning in other networks?

**Comment by alexander-rakhlin** [comment]
Hi,
To pick the neural network activation your images can be of arbitrary resolution too. As for transfer learning, this makes no sense in this situation.

**Comment by Suvi-dha** [comment]
ok, got your point. Thanks.
