### ISSUE TITLE
Model folder in source code

### ISSUE THREAD

**Issue by viewn** [alexander-rakhlin/ICIAR2018#9]
Dear all,

I can not see models folder in your source code structure. Could you help to share it?
   
 ├── models
    │   ├── LGBMs
    │   │   ├── Inception
    │   │   └── .........
    │   └── CNNs

Best regards,
Canh Nguyen

**Comment by izhangh** [comment]
Could you share the dataset?

**Comment by viewn** [comment]
Dear izhangh,

Dataset is from ICIAR 2018 Grand Challenge on Breast Cancer Histology Images
https://www.dropbox.com/s/1vwsfekuxc50cfm/ICIAR2018_data.zip?dl=1

**Comment by izhangh** [comment]
Thank you

**Comment by izhangh** [comment]
The LGBMs model may be in here: 
Dependencies
Python 3
Keras and Theano libraries. We did not test with Tensorflow backend, however it should work too.
[LightGBM](https://lightgbm.readthedocs.io/en/latest/index.html) package.
Standard scientific Python stack: NumPy, Pandas, SciPy, scikit-learn.
Other libraries: tqdm, six

**Comment by alexander-rakhlin** [comment]
Did you download models like suggested in README `python download_models.py`?
